### PR TITLE
Created new constituency alt-geoms

### PR DESCRIPTION
**Pull request by stepps00**
Created new alt-geometries for each of the 50 states (regions) in the US.

- Created new alt geometry files for each record
- Added a pointer to the alt geometry in the `src:alt_geom` slot

### CODE REVIEW

**Review by nvkelso — APPROVED** [review]
LGTM. I spot checked a few of these and they look good, including Alaska.

Don't think this needs any PIP work as the original geom remain the same, it's just the alt geom being added.

**Comment by thisisaaronland** [comment]
Cc @dphiffer – It's probably time to re-collapse all the `-us-REGION` constituencies in to this repo before things drift too far.

**Comment by thisisaaronland** [comment]
paging @dphiffer

**Comment by stepps00** [comment]
The constituency repos have been collapsed into this single repo, per [this commit](https://github.com/whosonfirst-data/whosonfirst-data-constituency-us/commit/bebd59f1a7aae5d74cb36e3c79bca846ebc2eccf).

Are we comfortable merging this PR now? I'd like to update records once this is merged.

**Comment by nvkelso** [comment]
Still looks good to me, @dphiffer for final merge question.

**Comment by dphiffer** [comment]
Hey everyone, sorry it took me so long to weigh in here. This is somewhat unrelated to the separate state-specific repos, which only had the state legislature records. In short, LGTM!

**Comment by dphiffer** [comment]
But yeah, I've merged all those other constituency repos as of this commit: https://github.com/whosonfirst-data/whosonfirst-data-constituency-us/commit/bebd59f1a7aae5d74cb36e3c79bca846ebc2eccf

**Pull request merged**
